### ISSUE TITLE
overwrite.yaml not overwriting configuration

### ISSUE THREAD

**Issue by KaelBaldwin** [covexo/devspace#314]
Probably I'm just making a mistake with my overwrite.yaml file somewhere, but I'm not seeing it.

I'm using Kaniko as the build engine. I'm overwriting my registry auth credentials, but it doesn't seem to be working. The image name I've overwritten isn't working either.

I even cloned the repo and attempted to debug this a bit (on master branch) and found something strange happening.

In `pkg/devspace/config/configutil/get.go` I dumped the config object in several places.

After line 84, when "overwriteConfigRaw" is first created. The content of that object was indeed my overwrite.yaml

But when I check the config object after the merge on line 88 (merging config and overwriteConfig) I see that the config object was not changed at all.

To help, here is my config file and overwrite file, with some adjustments to make it a little more generic.

at `./.devspace/config.yaml`
```
cluster:
  kubeContext: develop
  namespace: devspace
devSpace:
  deployments:
  - helm:
      chartPath: ./chart
    name: devspace-app
  ports:
  - labelSelector:
      release: devspace
    portMappings:
    - localPort: 80
      remotePort: 7001
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-app
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - vendor/
    - node_modules/
    - web/uploads/
images:
  default:
    name: devspace/app
    registry: custom
    build:
      kaniko:
        namespace: devspace
        cache: true
registries:
  custom:
    url: custom.registry.com
    auth:
      username: overwritethis
      password: andthis
version: v1alpha1
```

contents of `./.devspace/overwrite.yaml`
```
cluster:
  namespace: different-namespace
images:
  default:
    name: devspace/another-name
registries:
  custom:
    auth:
      username: RealUserName
      password: realpass
```
