### ISSUE TITLE
Services selectors

### ISSUE THREAD

**Issue by Gabrielbdd** [covexo/devspace#345]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
A declarative way to provide selectors for services in one place in the `config.yaml`

Currently, for use port-fowarding, sync, terminal, and the `devspace enter` command we should repeatedly provide the selector for the desired service:
```yaml
devSpace:
  ports:
    - labelSelector:
        app: api
  sync:
    - labelSelector:
        app: api
  terminal:
    labelSelector:
      app: api
```
and
```bash
devspace enter -l app=api
```
What if we could instead provide a way to map the services with they respective selectors and then just reuse it?
Ex:
```yaml
services:
  - name: api
    labelSelector:
      app: api
devSpace:
  ports:
    - service: api
  sync:
      service: api
  terminal:
    service: api
```
and
```bash
devspace enter api
```
or
```bash
devspace enter --service api
```
or
```bash
devspace enter -s api
```
I guess it will be much more clear to write `config.yaml` file and use the `devspace enter` command

/kind feature
