### ISSUE TITLE
How to fit devspace in container structure

### ISSUE THREAD

**Issue by musicformellons** [covexo/devspace#443]
I setup devspace and I can see it runs my project in my GKE cluster in a devspace pod. However, I used to run a manifest containing various deployments and services etc: my node api-backend together in one pod with my cloudsql database proxy, services, istio gateway, etc. I would like to use devspace (to start with) with the development of my node api-backend, but how do I fit this into my 'structure' as I now have just my devspace node api-backend container (which indeed syncs to my local code), but I would like it to be part of my total structure. To get this working it seems I maybe need to swap in my manifest my node api-backend deployment for one that sets up the devspace one. I do not know how to proceed. Does devspace fit my usecase? How do I use it then?

**Comment by LukasGentele** [comment]
Hi @musicformellons! Thanks for using DevSpace.

I am not quite sure what your exact scenario is like, so I will try to answer your question for 2 different scenarios:

## You only work on the api-backend project and the other one is just a container that needs to be deployed
When you initialize DevSpace for your project, it automatically creates a config for you within `.devspace/config.yaml`. There should be a section `devSpace.deployments` which describes everything that is being deployed during `devspace up`. By default, we deploy a helm chart which can be found in `chart/` and which is automatically created if the folder does not exist. You can easily edit any file within that chart. The Kubernetes manifests are in `chart/templates`, so you can add your db-proxy to the Deployment manifest in `chart/templates/deployment.yaml` by adding a new container definition to the `template.spec.containers` array in this manifest template.

More details regarding the config options can be found here: https://devspace.covexo.com/docs/configuration/config.yaml.html

If the Docker image for your db-proxy deployment should also be build and pushed with DevSpace, you can add the Dockerfile to `images` within the `.devspace/config.yaml` file within your project like this:
```
images:
  default:
    name: my-dockerhub-username/devspace
  dbProxy:
    name: my-dockerhub-username/db-proxy
    build:
      dockerfilePath: ./path/to/the/Dockerfile
      contextPath: ./path/to/the
```
More details on these options can be found here: https://devspace.covexo.com/docs/configuration/config.yaml.html#images-build

## You have a mono-repo and work on both projects
What is your folder structure? Is it a mono-repo with a structure like this:
```
  project/
  |- .devspace/
  |- api-backend/
  |- db-proxy/
```
If yes, you can simply add a deployment in your `project/.despace/config.yaml` file. If you are using kubectl manifest (= no helm), then your deployments section in the config file could look like this for the structure shown above:
```
deployments:
  - name: api-backend
    kubectl:
      manifests:
        - api-backend/my-manifest-folder
  - name: api-backend
    kubectl:
      manifests:
        - db-proxy/my-manifest-folder
```

## Otherwise
Let me know if anything I wrote was helpful. If not, it would be great if you provide more details about your case and I will try to help you as best as possible.
