### ISSUE TITLE
starting stopping server in container

### ISSUE THREAD

**Issue by musicformellons** [covexo/devspace#444]
I got [my setup working ](https://github.com/covexo/devspace/issues/443) and now was wondering: Is it possible to run a container without running its server. I now run my node api-backend container and it has a simplified liveliness check ('check if package.json is on the container) which works fine when I run the node server. However I would like start and stop the server from within the container (exec) instead of doing this via a dockerfile (or Helm) command. When I try to do e.g. 
```
ENTRYPOINT ["sh", "-c", "/bin/sleep 2"]
``` 
in my dockerfile the container keeps crashing and devspace up errors. Whereas this 
```
ENTRYPOINT ["sh", "-c", "/bin/sleep 2 && npm run debug"]
``` 
does work and devspace launches.

**Comment by musicformellons** [comment]
I got things working with 
```
ENTRYPOINT ["sh", "-c", "/bin/sleep 999999999"]
```
and can then start and ctrl+C from within the container. It is working very nicely!!

Two more questions:
1) How do I get another terminal into the container? Do I simply use another terminal and ```kubectl exec``` into it?
2) Is there also a way to run a entrypoint command from dockerfile which shows how my node server starts? Since now when I run ```ENTRYPOINT ["sh", "-c", "/bin/sleep 2 && npm run debug"]``` it runs in the background and I can not see the debug message etc.

**Comment by LukasGentele** [comment]
@musicformellons : That is exactly what `devspace up` is doing. There is a file in your helm chart called `chart/dev-overwrite.yaml` which overwrites the `chart/values.yaml`, so that the containers entrypoint will be sleep. You should not add the sleep in your Dockerfile but rather let `devspace up` overwrite the entrypoint within Kubernetes during deployment of the helm chart. 

If you added additional containers with names other than `default`, you can also use the `chart/dev-overwrite.yaml` and add another entry to `containers` to overwrite their entrypoints, too.

`devspace up` will by default start a terminal which then lets you run your command. 

If you are running `devspace up` already and want to open another terminal session, just run: `devspace enter`

Did this answer your question? If not, we can also talk on slack or do a small Skype session if that would be helpful. Let me know if I can close this issue or if you have any further questions.

**Comment by musicformellons** [comment]
Great stuff, thanks!

**Comment by musicformellons** [comment]
Mmmh, I tried to use ```chart/dev-overwrite.yaml```:
```
containers:
  default:
    command:
      - sleep
    args:
      - 2600000
```
And have in my dockerfile:
`ENTRYPOINT ["sh", "-c", "/bin/sleep 2 && npm run debug"]`

But when I do ```devspace up``` and then do ```npm run debug``` I get ```Error: listen EADDRINUSE :::8089```

When comment out the dev-overwrite code and replace my dockerfile with ```ENTRYPOINT ["sh", "-c", "/bin/sleep 2600000"]
``` I can do ```npm run debug``` and server starts properly. 

Any idea what's wrong? It looks like my dockerfile entrypoint was not overruled or something!?

**Comment by LukasGentele** [comment]
Ok, there are a couple of things I need to solve this:

1. Can you access the terminal when the error occurs? If yes, could you send me the output of `ps aux` and `lsof -i :8089` (if not installed, use `apt-get install lsof`)
2. Can you send me your deployment.yaml and your values.yaml? (please remove sensitive data before positing)

**Comment by musicformellons** [comment]
```
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 npm
   16 root      0:00 npm
   31 root      0:01 node /app/node_modules/.bin/nodemon src/
   59 root      0:00 ./ngrok start --none --log=stdout
   74 root      0:00 sh
   80 root      0:00 sh
   91 root      0:00 sh
  481 root      0:00 [ngrok]
 1192 root      0:08 /usr/local/bin/node src/
 1574 root      0:00 ps aux
```
and
```
/app # lsof -i :8089
COMMAND  PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    1192 root   11u  IPv6 2569848      0t0  TCP *:8089 (LISTEN)
```
By the way, I use ```FROM node:8-slim``` in my dockerfile. I noticed accidently that when I use ```FROM node:8-alpine``` instead, it does not give the address in use error and sleep behavior is 'as it should be'.

**Comment by LukasGentele** [comment]
Alright thanks. And what's the content of:
- .devspace/config.yaml
- chart/values.yaml
- chart/dev-overwrite.yaml
- chart/templates/deployment.yaml
? That would be really helpful. Make sure to remove sensitive data before posting.

**Comment by musicformellons** [comment]
.devspace/config.yaml
```
version: v1alpha1
cluster:
  kubeContext: gke_myproject_europe-west4-a_standard-cluster-1
  namespace: default
devSpace:
  deployments:
    - helm:
        chartPath: ./chart
        override: ./chart/dev-overwrite.yaml
      name: devspace-default
  ports:
    - portMappings:
        - localPort: 8089
          remotePort: 8089
        - localPort: 9229
          remotePort: 9229
      service: default
  services:
    - name: default
      labelSelector:
        devspace: default
  sync:
    - containerPath: /app
      localSubPath: ./
      service: default
      uploadExcludePaths:
        - Dockerfile
        - .devspace/
        - chart/
        - node_modules/
images:
  default:
    name: gcr.io/myproject/devspace
    createPullSecret: true
```

chart/values:
```
containers:
  default:
    image: "use this for devspace deploy, will be overwritten by devspace up"

pullSecrets: []
```

chart/dev-overwrite.yaml:
```
containers:
  default:
    command:
      - sleep
    args:
      - 2600000
```
chart/templates/deployment.yaml:
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    release: "{{ .Release.Name }}"
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp_pod
  template:
    metadata:
      annotations:
        revision: "{{ .Release.Revision }}"
      labels:
        app: myapp_pod
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}"
        devspace: "default"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: default
          image: "{{ .Values.containers.default.image }}"
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8089
            - name: my-generator
              containerPort: 8011
          env:
            - name: POSTGRES_DB_HOST
              value: 127.0.0.1:5432
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          livenessProbe:
            exec:
              command:
                - cat
                - /app/package.json
            periodSeconds: 5
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=myproject:europe-west4:mydb=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
```
chart/templates/external.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: external
  labels:
    app: myapp_pod
    release: "{{ .Release.Name }}"
    chartName: "{{ .Chart.Name }}"
    chartVersion: "{{ .Chart.Version }}"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8089
  selector:
    release: "{{ .Release.Name }}"
```
chart/templates/other.yaml:
```
kind: Service
apiVersion: v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp_pod
  ports:
    - name: http
      port: 8089
      targetPort: app-port
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: my-generator-client
  labels:
    app: myapp
spec:
  selector:
    app: myapp_pod
  ports:
    - name: http
      port: 8011
      targetPort: my-generator
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: myserver2
  labels:
    app: myserver2
spec:
  selector:
    app: myserver2_pod
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: t-rex-port
---
kind: Service
apiVersion: v1
metadata:
  name: my-generator-server
  labels:
    app: myserver2
spec:
  selector:
    app: myserver2_pod
  ports:
    - name: http
      protocol: TCP
      port: 8011
      targetPort: my-generator
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myserver2
  labels:
    app: myserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myserver2_pod
  template:
    metadata:
      labels:
        app: myserver2_pod
    spec:
      containers:
        - name: t-rex-server
          image: gcr.io/myproject/tttrex:v1
          imagePullPolicy: Always
          ports:
            - name: t-rex-port
              containerPort: 8081
            - name: my-generator
              containerPort: 8011
          env:
            - name: POSTGRES_DB_HOST
              value: 127.0.0.1:5432
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          livenessProbe:
            exec:
              command:
                - cat
                - /home/usr/osm.toml
            initialDelaySeconds:
            periodSeconds: 5
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=myproject:europe-west4:mydb=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        protocol: HTTP
        number: 80
      hosts:
        - "*"
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: myapp
spec:
  hosts:
    - "*"
  gateways:
    - myapp-gateway
  http:
    - match:
        - uri:
            prefix: /points
      route:
        - destination:
            host: myserver2
          weight: 100
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: myapp
          weight: 100
      websocketUpgrade: true
---
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: google-apis
spec:
  hosts:
    - "*.googleapis.com"
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  location: MESH_EXTERNAL
---
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: cloud-sql-instance
spec:
  hosts:
    - <my-cloudsql-database-ip>
  ports:
    - name: tcp
      number: 3307
      protocol: TCP
  location: MESH_EXTERNAL
```

**Comment by LukasGentele** [comment]
Ah I see. So, the issue is that the values from values.yaml and dev-overwrite.yaml will not automatically be used in your chart. They have to be used like this:
```
          command:
            {{- range $index, $command := .Values.containers.default.command }}
            - "{{ $command }}"
            {{- end }}
          args:
            {{- range $index, $arg := .Values.containers.default.args }}
            - "{{ $arg }}"
            {{- end }}
```
This is usually contained in the default chart/deployment.yaml, so you should add these lines to the main container where your application is running, e.g.:


**chart/deployment.yaml**
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    release: "{{ .Release.Name }}"
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp_pod
  template:
    metadata:
      annotations:
        revision: "{{ .Release.Revision }}"
      labels:
        app: myapp_pod
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}"
        devspace: "default"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: default
          image: "{{ .Values.containers.default.image }}"
          imagePullPolicy: Always
          command:
            {{- range $index, $command := .Values.containers.default.command }}
            - "{{ $command }}"
            {{- end }}
          args:
            {{- range $index, $arg := .Values.containers.default.args }}
            - "{{ $arg }}"
            {{- end }}
          ports:
            - name: app-port
              containerPort: 8089
            - name: my-generator
              containerPort: 8011
          env:
            - name: POSTGRES_DB_HOST
              value: 127.0.0.1:5432
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          livenessProbe:
            exec:
              command:
                - cat
                - /app/package.json
            periodSeconds: 5
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=myproject:europe-west4:mydb=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
```
That way, you should be able to run `devspace up` and only sleep should be running in your container, so that you can run `npm run debug` yourself in the container terminal. Does this fix your issue?
