### ISSUE TITLE
'portForwarding' correct?

### ISSUE THREAD

**Issue by musicformellons** [covexo/devspace#445]
On the webpage docs it gives [here](https://docs.devspace-cloud.com/docs/configuration/config.yaml.html):
```
  portForwarding:
  - labelSelector:
      release: devspace-default
    portMappings:
    - localPort: 3000
      remotePort: 3000
```
When I use portForwarding I get errors. Looks to me like this should be [ports](https://docs.devspace-cloud.com/docs/configuration/config.yaml.html#devspaceports) instead of portForwarding.
