### ISSUE TITLE
STDIN": error validating data: [apiVersion not set, kind not set]

### ISSUE THREAD

**Issue by musicformellons** [covexo/devspace#448]
Trying to have a setup without tiller & helm, using kubectl:
config.yaml:
```
version: v1alpha1
cluster:
  kubeContext: gke_myproject_europe-west4-a_standard-cluster-1
  namespace: default
devSpace:
  deployments:
    - name: api
      kubectl:
        manifests:
          - ./manifest/external.yaml
          - ./app/manifest/manifest.yaml
  ports:
    - service: app
      portMappings:
      - localPort: 8089
        remotePort: 8089
      - localPort: 9229
        remotePort: 9229
    - service: trex
      portMappings:
        - localPort: 8081
          remotePort: 8081
        - localPort: 8011
          remotePort: 8011
        - localPort: 9229
          remotePort: 9229
  services:
    - name: app
      labelSelector:
        devspace: app
    - name: trex
      labelSelector:
        devspace: trex
  sync:
    - service: app
      localSubPath: ./app
      containerPath: /app
      excludePaths:
      - ./Dockerfile
      - ./node_modules/
    - service: trex
      localSubPath: ./trex
      containerPath: /home/usr
      excludePaths:
        - ./Dockerfile
images:
  app:
    name: gcr.io/pqbq-224713/app
    build:
      dockerfilePath: ./app/Dockerfile
      contextPath: ./app
#    createPullSecret: true
  trex:
    name: gcr.io/pqbq-224713/trex
    build:
      dockerfilePath: ./trex/Dockerfile
      contextPath: ./trex
#    createPullSecret: true
```
./manifest/manifest.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: external
#  labels:
##    app: myapp_pod
#    release: "{{ .Release.Name }}"
#    chartName: "{{ .Chart.Name }}"
#    chartVersion: "{{ .Chart.Version }}"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8089
#  selector:
#    release: "{{ .Release.Name }}"
---
```
./app/manifest/manifest.yaml:
```
kind: Service
apiVersion: v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp_pod
  ports:
    - name: http
      port: 8089
      targetPort: app-port
      protocol: TCP
---
```
The manifest are created when running with kubectl directly, but when I do devspace up I get:
```
$ devspace up
[INFO]   Loading config .devspace/config.yaml with overwrite config .devspace/overwrite.yaml
[INFO]   Skip building image 'trex'
[INFO]   Skip building image 'app'
[INFO]   Deploying api with kubectl
service/external created                           
error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
[FATAL]  Error deploying devspace: Error deploying api: exit status 1
```
